@echo off
echo Cleaning up redundant documentation files...

del /Q ACTION_BUTTONS_ALWAYS_VISIBLE_FIX.md 2>nul
del /Q ACTION_BUTTONS_LOCATION.md 2>nul
del /Q AI_CONTEXT_FIX.md 2>nul
del /Q AI_RESPONSE_CONSISTENCY_FIX.md 2>nul
del /Q ALL_BUGS_FIXED.md 2>nul
del /Q ALL_MODES_FIXED_COMPLETE.md 2>nul
del /Q ALL_MODES_UPDATE_NEEDED.md 2>nul
del /Q APPWRITE_DOCUMENT_STORAGE_EXPLAINED.md 2>nul
del /Q APPWRITE_FILE_STORAGE_EXPLAINED.md 2>nul
del /Q APPWRITE_PDF_COLLECTIONS_SETUP.md 2>nul
del /Q APPWRITE_PDF_RESOURCES_SETUP.md 2>nul
del /Q APPWRITE_SETUP_GUIDE.md 2>nul
del /Q AUTOMATIC_VISUAL_GENERATION.md 2>nul
del /Q BORDERLESS_FULLSCREEN_COMPLETE.md 2>nul
del /Q CHAT_INPUT_FIXED_AT_BOTTOM.md 2>nul
del /Q CHAT_INTERFACE_EXPANDED.md 2>nul
del /Q CHAT_PERFORMANCE_OPTIMIZATION.md 2>nul
del /Q CLEAN_FILE_DISPLAY.md 2>nul
del /Q COMPLETE_CHART_TYPES_GUIDE.md 2>nul
del /Q COMPLETE_PDF_FEATURES.md 2>nul
del /Q COMPLETE_PROJECT_ANALYSIS.md 2>nul
del /Q COMPLETE_TESTING_CHECKLIST.md 2>nul
del /Q CRITICAL_FIX_NEEDED.md 2>nul
del /Q CURRENT_STATUS_COMPLETE.md 2>nul
del /Q DATABASE_RECOMMENDATIONS.md 2>nul
del /Q DEBUG_MESSAGES_NOT_PERSISTING.md 2>nul
del /Q DEBUG_PDF_LIBRARY_ISSUE.md 2>nul
del /Q DUAL_AI_QUICK_START.md 2>nul
del /Q EMOJI_TO_ICON_MIGRATION.md 2>nul
del /Q FILE_ATTACHMENT_STORAGE_STRATEGY.md 2>nul
del /Q FILE_DISPLAY_FIX.md 2>nul
del /Q FILE_PROCESSING_FINAL_FIX.md 2>nul
del /Q FILE_PROCESSING_FIX.md 2>nul
del /Q FINAL_FIX_COMPLETE.md 2>nul
del /Q FINAL_FIXES.md 2>nul
del /Q FINAL_IMPLEMENTATION_SUMMARY.md 2>nul
del /Q FINAL_PDF_SETUP.md 2>nul
del /Q FIX_CHATS_NOT_SHOWING.md 2>nul
del /Q FIXED_DATABASE_ISSUE.md 2>nul
del /Q FIXES_APPLIED.md 2>nul
del /Q FRESH_START_COMPLETE_SETUP.md 2>nul
del /Q FRESH_START_GUIDE.md 2>nul
del /Q FULLSCREEN_CHAT_IMPLEMENTED.md 2>nul
del /Q HEADER_BUTTONS_UPDATE.md 2>nul
del /Q HIGHLIGHTS_BOOKMARKS_GUIDE.md 2>nul
del /Q IMPLEMENTATION_SUMMARY.md 2>nul
del /Q MESSAGES_LIMIT_FIX.md 2>nul
del /Q MULTI_FORMAT_SUPPORT.md 2>nul
del /Q NETWORK_ERROR_HANDLING_IMPROVEMENTS.md 2>nul
del /Q NETWORK_RESILIENCE_FIX.md 2>nul
del /Q NEW_PDF_FEATURES.md 2>nul
del /Q PDF_ACCURACY_ALL_MODES.md 2>nul
del /Q PDF_CONTEXT_FIX_COMPLETE.md 2>nul
del /Q PDF_FEATURES_GUIDE.md 2>nul
del /Q PDF_FEATURES_LOCATION.md 2>nul
del /Q PDF_LIBRARY_FIX_SUMMARY.md 2>nul
del /Q PDF_RESOURCE_IMPLEMENTATION_COMPLETE.md 2>nul
del /Q PDF_RESOURCE_SYSTEM.md 2>nul
del /Q PDF_RESOURCES_FEATURE.md 2>nul
del /Q PDF_RESOURCES_IMPLEMENTATION_COMPLETE.md 2>nul
del /Q PDF_VIEWER_DECISION.md 2>nul
del /Q PERFORMANCE_OPTIMIZATIONS.md 2>nul
del /Q PINPOINT_ACCURACY_COMPLETE.md 2>nul
del /Q PROJECT_STATUS.md 2>nul
del /Q QUICK_START_GUIDE.md 2>nul
del /Q QUICK_START_PDF_RESOURCES.md 2>nul
del /Q QUICK_START_PDF_SETUP.md 2>nul
del /Q READY_FOR_UPDATES.md 2>nul
del /Q RECHARTS_FIX.md 2>nul
del /Q RECHARTS_INTEGRATION.md 2>nul
del /Q RECHARTS_MANDATORY.md 2>nul
del /Q RESTART_REQUIRED.md 2>nul
del /Q SESSION_MANAGEMENT_FEATURES.md 2>nul
del /Q SINGLE_NAVBAR_FIX.md 2>nul
del /Q STORAGE_INTEGRATION_COMPLETE.md 2>nul
del /Q STUDY_INTERFACE_COMPLETE.md 2>nul
del /Q STUDY_INTERFACE_IMPROVEMENTS.md 2>nul
del /Q STUDY_MODE_QUICK_START.md 2>nul
del /Q SYNTAX_ERRORS_FIXED.md 2>nul
del /Q SYSTEMATIC_BUG_ANALYSIS.md 2>nul
del /Q TROUBLESHOOTING_SSL_ERRORS.md 2>nul
del /Q TWO_SCENARIOS_COMPLETE.md 2>nul
del /Q UI_AND_WORKFLOW_IMPROVEMENTS.md 2>nul
del /Q UI_IMPROVEMENTS.md 2>nul
del /Q UX_ENHANCEMENTS_COMPLETE.md 2>nul
del /Q VISUAL_GENERATION_FEATURE.md 2>nul
del /Q VISUAL_GENERATION_IMPROVED.md 2>nul
del /Q VISUALIZATION_GUIDE_FOR_AI.md 2>nul
del /Q WHERE_ARE_ACTION_BUTTONS.md 2>nul
del /Q WHERE_ARE_PDF_FEATURES.md 2>nul

echo.
echo Cleanup complete!
echo.
echo Remaining documentation files:
dir /B *.md

pause
